[project]
name = "cookbook"
version = "0.1.0"
description = "Practical guides and examples."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "anthropic>=0.76.0",
    "dotenv>=0.9.9",
    "notebook>=7.5.2",
]
